#%RAML 1.0
title: 'Users API'
version: '1.0.0'
baseUri: http://localhost:3000
mediaType: application/json
types:
    User:
        type: object
        properties:
            id:
                required: true
                type: integer
            name:
                required: true
                type: string
    UserData:
        type: object
        properties:
            data:
                required: true
                type: array
                items: User
        example: |
          {
            "data": [
              { "id": 1, "name": "John Doe"},
              { "id": 2, "name": "Lorem Ipsum"}
            ]
          }
/users:
    get:
        description: List all Users matching query criteria.
        queryParameters:
            name:
                required: false
                type: string
                example: "John"
            id:
                required: false
                type: integer
                example: 1
        responses:
            200:
                body: UserData
